/**
 * 关卡数据。
 *
 * 地图图例：
 *   # 墙    . 地板    E 出口    ^ 尖刺
 *   @ 英雄  m 小兽    o 食人魔  X 食人魔王
 *   g 宝石  p 药水
 *
 * 每关的原则：只引入一个新概念，参考解必须真的能通关（由 tests/levels.test.ts 保证）。
 */

import type { LevelDef } from './types'

export const LEVELS: LevelDef[] = [
  {
    id: 'level-1',
    name: '第 1 关 · 地牢出口',
    subtitle: '顺序执行',
    objective: '走到出口。路上有食人魔挡道，先打倒它再前进。',
    hints: [
      '代码是一行一行往下执行的，写一行动作，英雄就走一步。',
      'hero.moveRight() 向右走一格；hero.attack(敌人) 攻击一次。',
      '先用 hero.findNearestEnemy() 找到敌人，再把它传给 attack。',
    ],
    newCommands: ['hero.moveRight()', 'hero.findNearestEnemy()', 'hero.attack(enemy)'],
    par: 10,
    enemiesStandStill: true,
    map: [
      '##########',
      '#@...o..E#',
      '##########',
    ],
    win: { killAll: true, reachExit: true },
    starter: ['// 让英雄走到出口吧', 'hero.moveRight()', ''].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'const enemy = hero.findNearestEnemy()',
      'hero.attack(enemy)',
      'hero.attack(enemy)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-2',
    name: '第 2 关 · 宝石走廊',
    subtitle: '循环与判断',
    objective: '捡光走廊上的宝石，并走到出口。小兽会主动扑过来。',
    hints: [
      'while (true) { ... } 会一直重复，直到任务完成或英雄倒下。',
      'if (条件) { ... } else { ... } 让英雄自己判断该打还是该走。',
      'hero.distanceTo(目标) 返回英雄到目标的曼哈顿距离。',
    ],
    newCommands: ['while (true)', 'if / else', 'hero.distanceTo(target)'],
    par: 16,
    map: [
      '#################',
      '#@..g..g..m..g.E#',
      '#################',
    ],
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: [
      '// 用 while 循环让英雄一直向前',
      'while (true) {',
      '  const enemy = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const enemy = hero.findNearestEnemy()',
      '  if (enemy && hero.distanceTo(enemy) <= 1) {',
      '    hero.attack(enemy)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-3',
    name: '第 3 关 · 食人魔王',
    subtitle: '属性与循环条件',
    objective: '打倒堵住通道的食人魔王，然后走到出口。',
    hints: [
      '敌人也是对象，enemy.health 是它当前的血量。',
      'while (boss.health > 0) { hero.attack(boss) } 可以一直打到它倒下。',
      'hero.pos.x / hero.pos.y 是英雄所在的格子坐标。',
    ],
    newCommands: ['enemy.health', 'hero.pos.x', 'while (条件)'],
    par: 21,
    enemiesStandStill: true,
    map: [
      '################',
      '#@...p..X.....E#',
      '################',
    ],
    win: { killAll: true, reachExit: true },
    starter: [
      '// 先走到食人魔王面前',
      'while (hero.pos.x < 7) {',
      '  hero.moveRight()',
      '}',
      '',
      '// 然后一直攻击，直到它的血量归零',
      '',
    ].join('\n'),
    solution: [
      'while (hero.pos.x < 7) {',
      '  hero.moveRight()',
      '}',
      'const boss = hero.findNearestEnemy()',
      'while (boss.health > 0) {',
      '  hero.attack(boss)',
      '}',
      'while (hero.pos.x < 14) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-4',
    name: '第 4 关 · 巡逻的守卫',
    subtitle: '判断距离',
    objective: '清掉整条走廊上的小兽，再走到出口。',
    hints: [
      '小兽发现英雄后会主动靠近，距离为 1 时才能攻击到它。',
      '与其硬冲，不如用 if/else 判断：够得着就打，够不着就走。',
      'hero.pos.x < 17 可以当作「还没到出口」的判断条件。',
    ],
    newCommands: ['if / else if / else', 'hero.pos'],
    par: 20,
    map: [
      '##################',
      '#@..m...m..m....E#',
      '##################',
    ],
    win: { killAll: true, reachExit: true },
    starter: ['// 一边前进一边判断', 'while (hero.pos.x < 17) {', '  ' , '}', ''].join('\n'),
    solution: [
      'while (hero.pos.x < 17) {',
      '  const enemy = hero.findNearestEnemy()',
      '  if (enemy && hero.distanceTo(enemy) <= 1) {',
      '    hero.attack(enemy)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-5',
    name: '第 5 关 · 函数的力量',
    subtitle: '封装重复动作',
    objective: '用函数把「前进两步再砍两刀」打包起来，清掉三个食人魔并到达出口。',
    hints: [
      'function 名字() { ... } 定义一段可以反复使用的代码。',
      '函数名后面加 () 就是调用它一次。',
      '中文也可以做函数名，写起来更像在描述战术。',
    ],
    newCommands: ['function 名字() { ... }', '调用函数'],
    par: 21,
    enemiesStandStill: true,
    map: [
      '################',
      '#@..o.o.o..g..E#',
      '################',
    ],
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: [
      '// 把重复的战术写成一个函数',
      'function 前进并战斗() {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'function 前进并战斗() {',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  const enemy = hero.findNearestEnemy()',
      '  if (enemy) {',
      '    hero.attack(enemy)',
      '    hero.attack(enemy)',
      '  }',
      '}',
      '前进并战斗()',
      '前进并战斗()',
      '前进并战斗()',
      'while (hero.pos.x < 14) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-6',
    name: '第 6 关 · 阵列清场',
    subtitle: '数组与 for...of',
    objective: '消灭竞技场里所有敌人，并捡走所有宝石（这里没有出口，全靠清场）。',
    hints: [
      'hero.findEnemies() 返回一个数组，hero.findItems() 同理。',
      'for (const enemy of hero.findEnemies()) { ... } 可以逐个处理数组里的元素。',
      '数组的 .length 是元素个数。',
    ],
    newCommands: ['hero.findEnemies()', 'for...of', '数组的 .length'],
    par: 22,
    map: [
      '##############',
      '#@..m...m....#',
      '#............#',
      '#....m...m..g#',
      '##############',
    ],
    win: { killAll: true, collectAll: true },
    starter: [
      '// 遍历所有敌人，够得着就打',
      'while (true) {',
      '  for (const enemy of hero.findEnemies()) {',
      '    ',
      '  }',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  for (const enemy of hero.findEnemies()) {',
      '    if (hero.distanceTo(enemy) <= 1) {',
      '      hero.attack(enemy)',
      '    }',
      '  }',
      '',
      '  const target = hero.findNearestEnemy()',
      '  if (target) {',
      '    if (target.pos.x > hero.pos.x) {',
      '      hero.moveRight()',
      '    } else if (target.pos.x < hero.pos.x) {',
      '      hero.moveLeft()',
      '    } else if (target.pos.y > hero.pos.y) {',
      '      hero.moveDown()',
      '    } else {',
      '      hero.moveUp()',
      '    }',
      '    continue',
      '  }',
      '',
      '  const item = hero.findNearestItem()',
      '  if (!item) {',
      '    break',
      '  }',
      '  if (item.pos.x > hero.pos.x) {',
      '    hero.moveRight()',
      '  } else if (item.pos.x < hero.pos.x) {',
      '    hero.moveLeft()',
      '  } else if (item.pos.y > hero.pos.y) {',
      '    hero.moveDown()',
      '  } else {',
      '    hero.moveUp()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-7',
    name: '第 7 关 · 自由练习',
    subtitle: '综合运用',
    objective: '这里是开放练习场：尖刺会扣血，药水能回血，敌人会主动巡逻。清场并捡光宝石。',
    hints: [
      '尖刺：走上去会掉 5 点血，尽量绕开。',
      '药水：走上去回复 25 点血。',
      '把前六关学到的东西组合起来吧。',
    ],
    par: 26,
    map: [
      '####################',
      '#@..^^..o...p......#',
      '#....g.....o.......#',
      '#.............g....#',
      '####################',
    ],
    win: { killAll: true, collectAll: true },
    starter: ['// 自由发挥：这里没有唯一答案', 'while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'hero.moveDown()',
      'while (true) {',
      '  const enemy = hero.findNearestEnemy()',
      '  if (enemy && hero.distanceTo(enemy) <= 1) {',
      '    hero.attack(enemy)',
      '    continue',
      '  }',
      '',
      '  const item = hero.findNearestItem()',
      '  const target = item || enemy',
      '  if (!target) {',
      '    break',
      '  }',
      '  if (target.pos.x > hero.pos.x) {',
      '    hero.moveRight()',
      '  } else if (target.pos.x < hero.pos.x) {',
      '    hero.moveLeft()',
      '  } else if (target.pos.y > hero.pos.y) {',
      '    hero.moveDown()',
      '  } else {',
      '    hero.moveUp()',
      '  }',
      '}',
    ].join('\n'),
  },
]

export function findLevel(id: string): LevelDef | undefined {
  return LEVELS.find((level) => level.id === id)
}
