/**
 * 关卡数据：5 个难度段、共 49 关。
 *
 * 分段原则（每一段只解锁一类新语法，其余语法会被 tutor.ts 拦下）：
 *   第 1 章  1~10  顺序编程：只练移动和攻击，不许写循环 / 判断 / 函数
 *   第 2 章 11~22  for 循环：把重复的 move 代码收成循环
 *   第 3 章 23~34  if 判断：看距离、看血量、看前方的格子做决定
 *   第 4 章 35~44  while + if 嵌套：自动探索、自动战斗
 *   第 5 章 45~49  综合大挑战：迷宫、怪物、尖刺一起上
 *
 * 地图图例：
 *   # 墙    . 地板    E 出口    ^ 尖刺
 *   @ 英雄  m 小兽    o 食人魔  X 食人魔王
 *   g 宝石  p 药水
 *
 * 每关的 solution 都会被 tests/levels.test.ts 真实执行一遍，
 * 通关不了会直接测试失败，所以不会出现「设计出来却过不去」的关卡。
 */

import type { ChapterDef, LanguageFeature, LevelDef } from './types'

/** 横墙：避免手数 # 的个数出错 */
const wall = (width: number) => '#'.repeat(width)

export const CHAPTERS: ChapterDef[] = [
  {
    id: 'ch1',
    name: '第 1 章 · 顺序编程',
    subtitle: '第 1~10 关',
    goal: '把想做的事按顺序写出来：走几步、砍几刀、走到出口',
    allow: ['变量', 'hero.moveXxx()', 'hero.attack()', 'hero.findNearestEnemy()'],
    forbidden: ['for', 'while', 'if', 'function'],
  },
  {
    id: 'ch2',
    name: '第 2 章 · for 循环',
    subtitle: '第 11~22 关',
    goal: '发现重复，用 for 循环把一长串重复代码收起来',
    allow: ['for 循环', '循环变量 i', '变量当循环次数'],
    forbidden: ['while', 'if', 'function'],
  },
  {
    id: 'ch3',
    name: '第 3 章 · if 判断',
    subtitle: '第 23~34 关',
    goal: '学会观察：前方有敌人吗？够得着吗？脚下是尖刺吗？',
    allow: [
      'if / else / else if',
      'hero.distanceTo()',
      'enemy.health',
      'hero.health',
      'hero.canMoveXxx()',
      'hero.lookXxx()',
    ],
    forbidden: ['while', 'function'],
  },
  {
    id: 'ch4',
    name: '第 4 章 · while + 嵌套 if',
    subtitle: '第 35~44 关',
    goal: '不再数次数：让英雄自己判断什么时候继续、什么时候停',
    allow: ['while 循环', '把 if 嵌进循环', 'break'],
    forbidden: ['function'],
  },
  {
    id: 'ch5',
    name: '第 5 章 · 综合大挑战',
    subtitle: '第 45~49 关',
    goal: '迷宫、怪物、尖刺混在一起，所有知识都可以用（含自定义函数）',
    allow: ['全部语法', '自定义函数'],
    forbidden: [],
  },
]

// ============================================================ 第 1 章 · 顺序编程
const CH1: LevelDef[] = [
  {
    id: 'level-1',
    chapter: 'ch1',
    name: '第 1 关 · 往前走',
    subtitle: '顺序执行',
    objective: '地牢的出口就在右边。让英雄一步一步走过去。',
    hints: [
      '代码是一行一行往下执行的：写一行 moveRight()，英雄就走一格。',
      '数一数英雄和出口之间隔了几格，就写几行。',
    ],
    newCommands: ['hero.moveRight()'],
    par: 10,
    map: [wall(12), '#@.......E.#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 让英雄走到出口', 'hero.moveRight()', ''].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-2',
    chapter: 'ch1',
    name: '第 2 关 · 向左走',
    subtitle: '反方向也是移动',
    objective: '出口在左边，用 moveLeft() 往回走。',
    hints: ['moveLeft() 向左走一格，和 moveRight() 刚好相反。'],
    newCommands: ['hero.moveLeft()'],
    par: 8,
    map: [wall(12), '#E.....@...#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 出口在左边', ''].join('\n'),
    solution: [
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
    ].join('\n'),
  },
  {
    id: 'level-3',
    chapter: 'ch1',
    name: '第 3 关 · 上下移动',
    subtitle: '四个方向都会走',
    objective: '出口在右下方：先往下走，再往右走。',
    hints: [
      'moveDown() 向下，moveUp() 向上。',
      '「先下后右」和「先右后下」都能到，两段顺序写出来就行。',
    ],
    newCommands: ['hero.moveDown()', 'hero.moveUp()'],
    par: 7,
    map: [wall(6), '#....#', '#....#', '#@...#', '#....#', '#...E#', wall(6)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 先往下，再往右', ''].join('\n'),
    solution: [
      'hero.moveDown()',
      'hero.moveDown()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-4',
    chapter: 'ch1',
    name: '第 4 关 · 路上有宝石',
    subtitle: '走过去就能捡',
    objective: '路上有两颗宝石，走过去就会自动捡起来，最后走到出口。',
    hints: [
      '宝石不用写代码去捡，走过去就自动捡到了。',
      '一路都写 moveRight()，让英雄一直往右走。',
    ],
    newCommands: ['走过宝石会自动捡'],
    par: 12,
    map: [wall(14), '#@..g...g..E.#', wall(14)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['// 一路往右走，宝石会自动捡起来', ''].join('\n'),
    solution: Array.from({ length: 10 }, () => 'hero.moveRight()').join('\n'),
  },
  {
    id: 'level-5',
    chapter: 'ch1',
    name: '第 5 关 · 前面有敌人',
    subtitle: '先认识敌人是谁',
    objective: '前面站着一只食人魔。先用 findNearestEnemy() 找到它，存进变量里，再去出口。',
    hints: [
      'findNearestEnemy() 的意思是「找到离我最近的敌人」，它会返回一个敌人。',
      '把找到的敌人存起来：const 敌人 = hero.findNearestEnemy()。',
      'const 的意思是「给它起个名字」，以后就用这个名字叫它。',
      '这一关不用打它：沿着上面那一行绕过去，就能到出口。',
    ],
    newCommands: ['const 敌人 = hero.findNearestEnemy()'],
    par: 11,
    map: [wall(12), '#@........E#', '#...o......#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      '// 先用 findNearestEnemy() 找到敌人，给它起个名字叫「敌人」',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.say("找到敌人啦")',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-6',
    chapter: 'ch1',
    name: '第 6 关 · 看清楚再出手',
    subtitle: '第一次攻击',
    objective: '走到食人魔旁边，再用 hero.attack(敌人) 打它。',
    hints: [
      'attack 的意思是「攻击」。括号里要写打谁。',
      'hero.attack(敌人) 就是「让英雄打那个叫敌人的家伙」。',
      '不能站到食人魔身上，走到它旁边就停下。',
      '食人魔有 20 点血，英雄一刀 10 点，所以要砍两刀。',
    ],
    newCommands: ['hero.attack(敌人)'],
    par: 17,
    map: ['################', '#@...o........E#', '################'],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      '// 先找到敌人',
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 走到它旁边，再打它',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-7',
    chapter: 'ch1',
    name: '第 7 关 · 看看它还有多少血',
    subtitle: '敌人有血条',
    objective: '食人魔比以前更结实。看看敌人的血量，一直打到它倒下。',
    hints: [
      '敌人的血量是 enemy.health，也就是「它还剩下多少血」。',
      '英雄一刀 10 点。想知道要砍几刀，就看它有多少血。',
      '血量变成 0，就表示它倒下了。',
      '这一关不用写 if，照着血条多砍几刀就好。',
    ],
    newCommands: ['enemy.health', 'hero.say("文字")'],
    par: 17,
    map: ['################', '#@....o.......E#', '################'],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      '// 先找到敌人',
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 先报一下它有多少血，再走到旁边打它',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.say(敌人.health)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-8',
    chapter: 'ch1',
    name: '第 8 关 · 一只一只来',
    subtitle: '两只敌人，两个变量',
    objective: '路上有两只敌人。走到第一只旁边打完它，再找下一只打完，最后去出口。',
    hints: [
      '打完第一只后，原来的变量还指着它。要重新找一次：再写一行 findNearestEnemy()。',
      '每找到一个敌人，就给它起个名字存起来，再 attack 这个名字。',
      '小兽只有 10 点血，一刀就倒。',
      '关键点：一场只能处理一个敌人，处理完再找下一个。',
    ],
    newCommands: ['重新调用 findNearestEnemy()'],
    par: 18,
    map: [wall(16), '#@..m....o....E#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      '// 第一只：小兽',
      'const 小兽 = hero.findNearestEnemy()',
      '',
      '// 打完它之后，再找下一只',
      '',
    ].join('\n'),
    solution: [
      'const 小兽 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(小兽)',
      'const 食人魔 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(食人魔)',
      'hero.attack(食人魔)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-9',
    chapter: 'ch1',
    name: '第 9 关 · 拐个弯',
    subtitle: '先横后竖',
    objective: '出口在右下角：先往右走到底，再往下走。',
    hints: ['先数横着要几步，再数竖着要几步。', '拐弯就是把两段移动按顺序写出来。'],
    par: 10,
    map: [wall(8), '#@.....#', '#......#', '#.....E#', wall(8)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 先右后下', ''].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveDown()',
      'hero.moveDown()',
    ].join('\n'),
  },
  {
    id: 'level-10',
    chapter: 'ch1',
    name: '第 10 关 · 第一章大考验',
    subtitle: '把学过的都用上',
    objective: '一条很长的通道，路上有宝石、药水、小兽和食人魔。按顺序走完它。',
    hints: [
      '宝石和药水不用特意去捡，走过去就自动到手了。',
      '先找到第一只敌人，打完再重新 findNearestEnemy() 找下一只。',
      'hero.health 是英雄自己的血量，药水会把血补回来。',
      '这条路很长，慢慢写。写完就进入第 2 章啦。',
    ],
    newCommands: ['hero.health'],
    par: 26,
    map: [wall(24), '#@..g..m...p...o...g..E#', wall(24)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: [
      '// 第一只：小兽',
      'const 小兽 = hero.findNearestEnemy()',
      '',
      '// 打完它，再找下一只',
      '',
    ].join('\n'),
    solution: [
      'const 小兽 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(小兽)',
      'const 食人魔 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.say(hero.health)',
      'hero.attack(食人魔)',
      'hero.attack(食人魔)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
]

// ============================================================ 第 2 章 · for 循环
const CH2: LevelDef[] = [
  {
    id: 'level-11',
    chapter: 'ch2',
    name: '第 11 关 · 重复的力量',
    subtitle: 'for 循环入门',
    objective: '还是那条长走廊，这次用 for 循环代替 17 行 moveRight()。',
    hints: [
      'for (let i = 0; i < 次数; i++) { ... } 里的代码会重复执行「次数」遍。',
      '数一数要走多少格，把它写进 i < 多少。',
    ],
    newCommands: ['for (let i = 0; i < 次数; i++) { ... }'],
    par: 19,
    map: [wall(20), '#@...........g....E#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 17; i++) {', '  hero.moveRight()', '}', ''].join('\n'),
    solution: ['for (let i = 0; i < 17; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-12',
    chapter: 'ch2',
    name: '第 12 关 · 两段路',
    subtitle: '一个循环管一段',
    objective: '先向右走到头，再向下走到底。两段路各写一个循环。',
    hints: ['两段次数不一样，就写两个循环。'],
    par: 20,
    map: [wall(20), '#@.................#', '#..................#', '#................E.#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['for (let i = 0; i < 16; i++) {', '  hero.moveRight()', '}', '', '// 再往下走', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 16; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 2; i++) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-13',
    chapter: 'ch2',
    name: '第 13 关 · 宝石队列',
    subtitle: '循环顺手捡宝石',
    objective: '四颗宝石整齐排在路上，用一个循环走到底。',
    hints: ['宝石是等距摆放的，所以一个循环就能全捡到。'],
    par: 17,
    map: [wall(19), '#@..g..g..g..g..E.#', wall(19)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 15; i++) {', '  hero.moveRight()', '}', ''].join('\n'),
    solution: ['for (let i = 0; i < 15; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-14',
    chapter: 'ch2',
    name: '第 14 关 · 连击',
    subtitle: '用循环砍到倒下',
    objective: '食人魔王就站在旁边，血很厚。用循环连砍 6 刀，再走到出口。',
    hints: [
      '先用 findNearestEnemy() 把它存进变量，再在循环里反复攻击。',
      '战斗中它会还手，英雄掉血是正常的。',
    ],
    newCommands: ['enemy.health'],
    par: 26,
    map: [wall(20), '#@X...............E#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['const boss = hero.findNearestEnemy()', '', '// 在循环里攻击它', ''].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'for (let i = 0; i < 6; i++) {',
      '  hero.attack(boss)',
      '}',
      'for (let i = 0; i < 17; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-15',
    chapter: 'ch2',
    name: '第 15 关 · 走两步，砍两刀',
    subtitle: '循环里的固定节奏',
    objective: '四个食人魔等距离站岗。每轮「走两格 + 砍两刀」，循环四轮。',
    hints: ['循环体里可以写多行代码，它们会整段重复。'],
    par: 26,
    map: [wall(20), '#@..o.o.o.o.....E..#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 4; i++) {', '  // 走两步 + 砍两刀', '}', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  const 敌人 = hero.findNearestEnemy()',
      '  hero.attack(敌人)',
      '  hero.attack(敌人)',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-16',
    chapter: 'ch2',
    name: '第 16 关 · 边报数边前进',
    subtitle: '循环变量 i 会变',
    objective: '每捡一颗宝石就报一次数，用 hero.say() 说出现在是第几颗。',
    hints: [
      '循环变量 i 每一轮都会变化，可以直接拼进字符串。',
      '字符串拼接用 + ："第 " + i + " 颗宝石"。',
    ],
    newCommands: ['hero.say("文字")', '字符串拼接 "a" + i'],
    par: 19,
    map: [wall(21), '#@.g..g..g..g..g..E.#', wall(21)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['for (let i = 1; i <= 5; i++) {', '  // 报数，然后走三格', '}', ''].join('\n'),
    solution: [
      'for (let i = 1; i <= 5; i++) {',
      '  hero.say("第 " + i + " 颗宝石")',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '}',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-17',
    chapter: 'ch2',
    name: '第 17 关 · L 形通道',
    subtitle: '两段不同次数',
    objective: '先向右走 5 格，再向下走 3 格到出口。',
    hints: ['两个循环，次数分别写在各自的条件里。'],
    par: 10,
    map: [wall(16), '#@.............#', '#..............#', '#..............#', '#.....E........#', wall(16)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 向右 5 格', '', '// 向下 3 格', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 5; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 3; i++) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-18',
    chapter: 'ch2',
    name: '第 18 关 · 次数用变量',
    subtitle: '把数字取个名字',
    objective: '先用 let 把步数记下来，再让循环按这个变量走。',
    hints: [
      'let 步数 = 13 之后，循环条件里就能写 i < 步数。',
      '以后想让英雄多走两格，只改数字那一行就行。',
    ],
    par: 15,
    map: [wall(20), '#@..........g.E....#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['const 步数 = 13', '', 'for (let i = 0; i < 步数; i++) {', '  hero.moveRight()', '}', ''].join('\n'),
    solution: ['const 步数 = 13', 'for (let i = 0; i < 步数; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-19',
    chapter: 'ch2',
    name: '第 19 关 · 一排小兽',
    subtitle: '循环里的一刀流',
    objective: '四只小兽等距排列。每轮走两格、砍一刀，循环四轮。',
    hints: ['小兽只有 10 点血，一刀就够。'],
    par: 21,
    map: [wall(20), '#@..m.m.m.m.....E..#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 4; i++) {', '  // 走两格 + 砍一刀', '}', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  const 敌人 = hero.findNearestEnemy()',
      '  hero.attack(敌人)',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-20',
    chapter: 'ch2',
    name: '第 20 关 · 长路用循环',
    subtitle: '一行代码走到底',
    objective: '这次走廊有 21 格，用循环一行搞定。',
    hints: ['回想第 9 关你写了多少行——这就是循环的价值。'],
    par: 24,
    map: [wall(24), '#@....................E#', wall(24)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['for (let i = 0; i < 21; i++) {', '  hero.moveRight()', '}', ''].join('\n'),
    solution: ['for (let i = 0; i < 21; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-21',
    chapter: 'ch2',
    name: '第 21 关 · 先赶路再战斗',
    subtitle: '循环 + 战斗',
    objective: '先走 6 格（顺路捡宝石），再砍倒食人魔，最后走到出口。',
    hints: ['循环不只能包移动，也能包攻击。'],
    par: 16,
    map: [wall(16), '#@..g...o....E.#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: ['// 第一段：赶路', '', '// 第二段：战斗', '', '// 第三段：继续赶路', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'const 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-22',
    chapter: 'ch2',
    name: '第 22 关 · 第二章考验',
    subtitle: '走 - 打 - 走 - 打 - 走',
    objective: '宝石和食人魔交替出现，把整条路线用循环串起来。',
    hints: ['把路线拆成「赶路」和「战斗」两种段落，交替写。'],
    par: 29,
    map: [wall(26), '#@..g...o...g...o...g..E.#', wall(26)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: ['// 走 6 格 → 打 2 刀 → 走 8 格 → 打 2 刀 → 走 8 格', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'let 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
      '敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 3 章 · if 判断
const CH3: LevelDef[] = [
  {
    id: 'level-23',
    chapter: 'ch3',
    name: '第 23 关 · 够得着才出手',
    subtitle: 'if 判断入门',
    objective: '食人魔离得有点远。先判断距离：太远就先走近一步，再动手。',
    hints: [
      'if (hero.distanceTo(敌人) > 1) { ... } 里的代码只在条件成立时执行。',
      '距离是曼哈顿距离：横着差几格 + 竖着差几格。',
    ],
    newCommands: ['if (条件) { ... }', 'hero.distanceTo(敌人)'],
    par: 13,
    map: [wall(14), '#@.o......E..#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 如果够不着，就先走近一步',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'if (hero.distanceTo(敌人) > 1) {',
      '  hero.moveRight()',
      '}',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-24',
    chapter: 'ch3',
    name: '第 24 关 · 够得着就打',
    subtitle: 'if / else 二选一',
    objective: '路上有小兽也有食人魔。每走一步判断一次：够得着就打，够不着就走。',
    hints: [
      'if (条件) { 打 } else { 走 } —— 两个分支只会执行一个。',
      '循环次数写多一点没关系，走到出口任务就完成了。',
    ],
    newCommands: ['if / else'],
    par: 18,
    map: [wall(17), '#@..o....m....E.#', wall(17)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 24; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 24; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-25',
    chapter: 'ch3',
    name: '第 25 关 · 打到它倒下',
    subtitle: '读敌人的血量',
    objective: '食人魔就站在面前。用 enemy.health 判断它是否还活着，倒下了就停手。',
    hints: [
      'enemy.health 是当前血量，掉到 0 就表示已经倒下。',
      'if (boss.health > 0) 只在它还活着的时候攻击。',
    ],
    newCommands: ['if (enemy.health > 0)'],
    par: 21,
    map: [wall(20), '#@o...............E#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const boss = hero.findNearestEnemy()',
      '',
      'for (let i = 0; i < 10; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'for (let i = 0; i < 10; i++) {',
      '  if (boss.health > 0) {',
      '    hero.attack(boss)',
      '  }',
      '}',
      'for (let i = 0; i < 17; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-26',
    chapter: 'ch3',
    name: '第 26 关 · 撞墙就转弯',
    subtitle: '用 canMove 探路',
    objective: '通道走到尽头要往下拐。用 hero.canMoveRight() 判断右边能不能走。',
    hints: [
      'canMoveRight() 返回 true / false：右边是墙、或者站着人，就是 false。',
      '能右转就右转，不能就往下走。',
    ],
    newCommands: ['hero.canMoveRight()', 'hero.canMoveDown()'],
    par: 8,
    map: [wall(6), '#@...#', '#....#', '#....#', '#...E#', wall(6)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'for (let i = 0; i < 12; i++) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    ',
      '  }',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 12; i++) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.moveDown()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-27',
    chapter: 'ch3',
    name: '第 27 关 · 看到尖刺就绕开',
    subtitle: '用 look 观察前方',
    objective: '前方有两格尖刺，踩上去会掉血。用 hero.lookRight() 看清是什么再决定。',
    hints: [
      'hero.lookRight() 返回前方那一格的内容："空地"、"墙"、"尖刺"、"敌人"、"物品"、"出口"。',
      '发现尖刺就先下到安全的一行绕过去。',
    ],
    newCommands: ['hero.lookRight() === "尖刺"'],
    par: 17,
    map: [wall(14), '#@..^^...o..E#', '#............#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.moveRight()',
      'if (hero.lookRight() === "尖刺") {',
      '  hero.moveDown()',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'if (hero.lookRight() === "尖刺") {',
      '  hero.moveDown()',
      '}',
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'const 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveUp()',
      'for (let i = 0; i < 3; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-28',
    chapter: 'ch3',
    name: '第 28 关 · 别踩尖刺',
    subtitle: '尖刺挡路，绕一圈',
    objective: '通道上有两格尖刺。从下面那行走过去，再从右边回到出口。',
    hints: ['先用 lookRight() 确认尖刺位置，再决定什么时候下去、什么时候上来。'],
    par: 13,
    map: [wall(12), '#@..^^....E#', '#..........#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.moveRight()',
      'if (hero.lookRight() === "尖刺") {',
      '  hero.moveDown()',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'if (hero.lookRight() === "尖刺") {',
      '  hero.moveDown()',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
      'hero.moveUp()',
    ].join('\n'),
  },
  {
    id: 'level-29',
    chapter: 'ch3',
    name: '第 29 关 · 三种情况',
    subtitle: 'if / else if / else',
    objective: '一路向右，前方可能是敌人、尖刺或者墙。三种情况，三种做法。',
    hints: [
      'else if 接着判断第二种情况，顺序从特殊到普通。',
      '遇到尖刺往下绕，遇到墙往上走，其他情况就往前走。',
    ],
    newCommands: ['if / else if / else'],
    par: 21,
    map: [wall(16), '#@..o..^^...o.E#', '#..............#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 40; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 40; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-30',
    chapter: 'ch3',
    name: '第 30 关 · 受伤了先补血',
    subtitle: '看自己的血量',
    objective: '出门先挨了一下。用 hero.health 判断是否受伤，受伤就先去下面那行喝药水。',
    hints: [
      'hero.health 是当前血量，hero.maxHealth 是上限（100）。',
      'if (hero.health < hero.maxHealth) 表示「掉过血」。',
    ],
    newCommands: ['hero.maxHealth'],
    par: 23,
    map: [wall(18), '#@.m....o.......E#', '#....p...........#', wall(18)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.attack(hero.findNearestEnemy())',
      '',
      '// 受伤了就下去喝药水',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.attack(hero.findNearestEnemy())',
      'if (hero.health < hero.maxHealth) {',
      '  hero.moveDown()',
      '  for (let i = 0; i < 3; i++) {',
      '    hero.moveRight()',
      '  }',
      '  hero.moveUp()',
      '}',
      'for (let i = 0; i < 2; i++) {',
      '  hero.moveRight()',
      '}',
      'hero.attack(hero.findNearestEnemy())',
      'hero.attack(hero.findNearestEnemy())',
      'for (let i = 0; i < 9; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-31',
    chapter: 'ch3',
    name: '第 31 关 · 守卫队',
    subtitle: '循环里套判断',
    objective: '三只小兽守在通道上。一边前进一边判断：够得着就砍。',
    hints: ['和第 24 关思路一样，只是敌人多了几个。'],
    par: 25,
    map: [wall(22), '#@..m....m....m.....E#', wall(22)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-32',
    chapter: 'ch3',
    name: '第 32 关 · 尖刺回廊',
    subtitle: '整条上排都是尖刺',
    objective: '上面那行全是尖刺。先下到安全的一行，走到尽头再上来。',
    hints: [
      'hero.lookRight() === "墙" 表示前面没路了。',
      '先往下走一格，然后一直向右，撞墙就往上。',
    ],
    newCommands: ['hero.lookRight() === "墙"'],
    par: 21,
    map: [wall(20), '#@..^^^^^^^^......E#', '#..................#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'hero.moveDown()',
      '',
      'for (let i = 0; i < 25; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveDown()',
      'for (let i = 0; i < 25; i++) {',
      '  if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-33',
    chapter: 'ch3',
    name: '第 33 关 · 先补给再决战',
    subtitle: '次序很重要',
    objective: '前面是食人魔王，路上有瓶药水。先喝药水再开打，才扛得住。',
    hints: [
      '食人魔王 60 点血、每下 12 点伤害，硬拼会很痛。',
      '用 if (boss.health > 0) 控制攻击，血空了就不再挥刀。',
    ],
    par: 24,
    map: [wall(20), '#@...p....X.....E..#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const boss = hero.findNearestEnemy()',
      '',
      '// 先去喝药水',
      '',
      '// 再和它决战',
      '',
    ].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 8; i++) {',
      '  if (boss.health > 0) {',
      '    hero.attack(boss)',
      '  }',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-34',
    chapter: 'ch3',
    name: '第 34 关 · 第三章考验',
    subtitle: '一条长防线',
    objective: '三个食人魔依次守着通道，一路判断一路推进。',
    hints: ['套路就是：够得着就打，够不着就走，走到出口自动结束。'],
    par: 30,
    map: [wall(25), '#@...o....o....o......E.#', wall(25)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 4 章 · while + 嵌套 if
const CH4: LevelDef[] = [
  {
    id: 'level-35',
    chapter: 'ch4',
    name: '第 35 关 · 一直向前',
    subtitle: 'while (true)',
    objective: '不用数格子了：让英雄一直往前走，走到出口任务就自动结束。',
    hints: [
      'while (true) { ... } 会一直重复，直到任务完成或英雄倒下。',
      '不用担心停不下来：踩上出口的那一瞬间程序就结束了。',
    ],
    newCommands: ['while (true) { ... }'],
    par: 18,
    map: [wall(20), '#@...............E.#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['while (true) {', '  hero.moveRight()', '}', ''].join('\n'),
    solution: ['while (true) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-36',
    chapter: 'ch4',
    name: '第 36 关 · 走到指定位置',
    subtitle: 'while + 坐标条件',
    objective: '先向右走到第 10 格，再向下走到出口。条件写在 while 里。',
    hints: [
      'hero.pos.x 是当前列号，hero.pos.y 是行号。',
      'while (hero.pos.x < 10) 表示「还没到第 10 列就继续走」。',
    ],
    newCommands: ['while (hero.pos.x < 10)', 'hero.pos.x / hero.pos.y'],
    par: 14,
    map: [wall(16), '#@.............#', '#..............#', '#..............#', '#.........E....#', wall(16)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'while (hero.pos.x < 10) {',
      '  hero.moveRight()',
      '}',
      '',
      '// 再往下走到出口',
      '',
    ].join('\n'),
    solution: [
      'while (hero.pos.x < 10) {',
      '  hero.moveRight()',
      '}',
      'while (hero.pos.y < 4) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-37',
    chapter: 'ch4',
    name: '第 37 关 · 边走边打',
    subtitle: 'if 嵌在 while 里',
    objective: '小兽会主动扑过来。循环里判断：够得着就打，够不着就继续走。',
    hints: ['这就是自动战斗的雏形：一个 while 包住「观察 → 决定 → 行动」。'],
    newCommands: ['while + if 嵌套'],
    par: 21,
    map: [wall(20), '#@..m...m...m....E.#', wall(20)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-38',
    chapter: 'ch4',
    name: '第 38 关 · 收集到底',
    subtitle: 'while + findNearestItem',
    objective: '用 while (hero.findNearestItem()) 一直捡，直到宝石全都到手。',
    hints: [
      'findNearestItem() 找不到东西时返回 null，条件不成立，循环就结束了。',
      '捡完之后还要走到出口。',
    ],
    newCommands: ['while (hero.findNearestItem())'],
    par: 18,
    map: [wall(20), '#@..g...g...g....E.#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: [
      'while (hero.findNearestItem()) {',
      '  hero.moveRight()',
      '}',
      '',
      '// 再去出口',
      '',
    ].join('\n'),
    solution: [
      'while (hero.findNearestItem()) {',
      '  hero.moveRight()',
      '}',
      'while (hero.pos.x < 18) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-39',
    chapter: 'ch4',
    name: '第 39 关 · 打到它倒下',
    subtitle: 'while + 血量条件',
    objective: '用 boss.health > 0 当作循环条件，打到它倒下为止。',
    hints: ['while (boss.health > 0) 比写死「打 6 刀」更聪明：换个血量的敌人也不用改代码。'],
    newCommands: ['while (boss.health > 0)'],
    par: 26,
    map: [wall(20), '#@X...............E#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const boss = hero.findNearestEnemy()',
      '',
      'while (boss.health > 0) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'while (boss.health > 0) {',
      '  hero.attack(boss)',
      '}',
      'while (hero.pos.x < 18) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-40',
    chapter: 'ch4',
    name: '第 40 关 · 迷宫入门',
    subtitle: '自动探索',
    objective: '看不见全图也没关系：能右转就右转，不能就往下走，一路摸到出口。',
    hints: [
      'while (true) 里先判断 canMoveRight()，再判断 canMoveDown()，都不行就 break 结束。',
      'break 表示跳出循环。',
    ],
    newCommands: ['break'],
    par: 11,
    map: [wall(10), '#@.......#', '#.#####..#', '#.......E#', wall(10)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'while (true) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-41',
    chapter: 'ch4',
    name: '第 41 关 · 尖刺回廊（自动版）',
    subtitle: 'while + look',
    objective: '上面一行全是尖刺。先下到安全通道，一路向右，撞墙就上。',
    hints: ['这次不用数次数，把第 32 关的思路换成 while 就行。'],
    par: 21,
    map: [wall(20), '#@..^^^^^^^^......E#', '#..................#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'hero.moveDown()',
      '',
      'while (true) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveDown()',
      'while (true) {',
      '  if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-42',
    chapter: 'ch4',
    name: '第 42 关 · 迷宫进阶',
    subtitle: '迷宫 + 守卫',
    objective: '迷宫里藏着一只小兽。先解决它，再继续摸索出口。',
    hints: ['把「打敌人」放在最优先：距离 1 就先砍，其次才是走路。'],
    par: 14,
    map: [wall(12), '#@....m....#', '#.#######..#', '#.........E#', wall(12)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-43',
    chapter: 'ch4',
    name: '第 43 关 · 巡逻队',
    subtitle: '会追人的敌人',
    objective: '三种敌人都会主动扑上来。一路推进，把它们清干净。',
    hints: [
      '敌人会跟着你走，所以不用追它，站住反击也行。',
      '走到墙边还有敌人没解决时，用 hero.wait() 原地等它过来。',
    ],
    newCommands: ['hero.wait()'],
    par: 29,
    map: [wall(24), '#@...o....m....o......E#', wall(24)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.wait()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-44',
    chapter: 'ch4',
    name: '第 44 关 · 第四章考验',
    subtitle: '看路 + 打架',
    objective: '尖刺和守卫一起出现。先绕尖刺、顺手清怪，最后爬上出口。',
    hints: ['判断顺序很重要：能打就打，其次躲尖刺，再其次往前走，最后才考虑上下。'],
    par: 25,
    map: [wall(22), '#@..^^..m...........E#', '#....................#', wall(22)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 5 章 · 综合大挑战
const CH5: LevelDef[] = [
  {
    id: 'level-45',
    chapter: 'ch5',
    name: '第 45 关 · 迷宫 I',
    subtitle: '综合挑战',
    objective: '尖刺、拐角、守卫都在。用一套「先看、再打、再走」的循环走出去。',
    hints: [
      '判断顺序建议：够得着就打 → 前方尖刺就绕 → 能右转就右转 → 能下行就下行。',
      '这一章开始可以用 function 把常用判断打包起来。',
    ],
    par: 17,
    map: [wall(14), '#@..^^.......#', '#....##......#', '#....##......#', '#.......m...E#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  const 敌人 = hero.findNearestEnemy()', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-46',
    chapter: 'ch5',
    name: '第 46 关 · 怪物军团',
    subtitle: '血量和药水',
    objective: '一队怪物会主动扑上来，路上有瓶药水。血少了先补，再继续推进。',
    hints: [
      'if (hero.health < 60) 可以当作「该补血了」的信号。',
      '被围住时先对付最近的敌人，别硬冲。',
    ],
    par: 28,
    map: [wall(24), '#@..m...o...m...p.....E#', wall(24)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  const 敌人 = hero.findNearestEnemy()', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.health < 60 && hero.findNearestItem()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.wait()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-47',
    chapter: 'ch5',
    name: '第 47 关 · 尖刺回廊 II',
    subtitle: '会受点伤的路线',
    objective: '上排尖刺很长，下排被墙截断。找机会穿过去，拿上药水再走到出口。',
    hints: [
      '有时不得不踩一次尖刺（-5 血），这比绕远路划算。',
      '判断顺序：打怪 → 尖刺就下 → 能右就右 → 能上就上 → 能下就下。',
    ],
    par: 26,
    map: [wall(24), '#@..^^^^^^^^....p.....E#', '#...........##.........#', wall(24)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-48',
    chapter: 'ch5',
    name: '第 48 关 · 迷宫 II',
    subtitle: '两段下降',
    objective: '这条迷宫要连着往下拐两次，路上还藏着守卫。',
    hints: ['迷宫里不需要「向左」：一路右、下、上就能到出口。'],
    par: 18,
    map: [wall(16), '#@.....#.......#', '#......#.......#', '#......#.......#', '#.....^^..m..E.#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-49',
    chapter: 'ch5',
    name: '第 49 关 · 终局：地牢深处',
    subtitle: '全部知识',
    objective: '最后一战：走廊上有两只怪、一瓶药水，尽头是一段向下的秘密通道。',
    hints: [
      '把所有套路串起来：观察、判断、行动，循环到出口为止。',
      '想想能不能用 function 把「打怪」这一段包起来，代码会更短。',
    ],
    par: 30,
    map: [
      wall(24),
      '#@..m....o.......p.....#',
      '#.###################..#',
      '#.###################..#',
      '#.....................E#',
      wall(24),
    ],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
]

export const LEVELS: LevelDef[] = [...CH1, ...CH2, ...CH3, ...CH4, ...CH5]

// 把章节的语法锁同步到每一关，避免每关重复写一遍
for (const level of LEVELS) {
  const chapter = CHAPTERS.find((item) => item.id === level.chapter)
  level.forbidden = (chapter?.forbidden ?? []) as LanguageFeature[]
}

export function findLevel(id: string): LevelDef | undefined {
  return LEVELS.find((level) => level.id === id)
}

export function findChapter(id: string): ChapterDef | undefined {
  return CHAPTERS.find((chapter) => chapter.id === id)
}

export function levelsOfChapter(chapterId: string): LevelDef[] {
  return LEVELS.filter((level) => level.chapter === chapterId)
}
