/**
 * 关卡数据：5 个难度段、共 49 关。
 *
 * 分段原则（每一段只解锁一类新语法，其余语法会被 tutor.ts 拦下）：
 *   第 1 章  1~10  顺序编程：只练移动和攻击，不许写循环 / 判断 / 函数
 *   第 2 章 11~22  for 循环：把重复的 move 代码收成循环
 *   第 3 章 23~34  if 判断：看距离、看血量、看前方的格子做决定
 *   第 4 章 35~44  while + if 嵌套：自动探索、自动战斗
 *   第 5 章 45~49  综合大挑战：迷宫、怪物、尖刺一起上
 *
 * 地图图例：
 *   # 墙    . 地板    E 出口    ^ 尖刺
 *   @ 英雄  m 小兽    o 食人魔  X 食人魔王
 *   g 宝石  p 药水
 *
 * 每关的 solution 都会被 tests/levels.test.ts 真实执行一遍，
 * 通关不了会直接测试失败，所以不会出现「设计出来却过不去」的关卡。
 */

import type { ChapterDef, LanguageFeature, LevelDef } from './types'

/** 横墙：避免手数 # 的个数出错 */
const wall = (width: number) => '#'.repeat(width)

export const CHAPTERS: ChapterDef[] = [
  {
    id: 'ch1',
    name: '第 1 章 · 顺序编程',
    subtitle: '第 1~10 关',
    goal: '把想做的事按顺序写出来：走几步、砍几刀、走到出口',
    allow: ['变量 const', 'hero.moveXxx()', 'hero.say()', 'hero.findNearestEnemy()', 'hero.attack()', 'enemy.health'],
    forbidden: ['for', 'while', 'if', 'function'],
  },
  {
    id: 'ch2',
    name: '第 2 章 · for 循环',
    subtitle: '第 11~22 关',
    goal: '发现重复，用 for 循环把一长串重复代码收起来',
    allow: ['for 循环', '循环变量 i', '变量当循环次数'],
    forbidden: ['while', 'if', 'function'],
  },
  {
    id: 'ch3',
    name: '第 3 章 · if 判断',
    subtitle: '第 23~34 关',
    goal: '学会观察：前方有敌人吗？够得着吗？脚下是尖刺吗？',
    allow: [
      'hero.distanceTo()',
      'if / else / else if',
      '&&（并且）',
      'hero.health',
      'hero.maxHealth',
      'hero.canMoveXxx()',
      'hero.lookXxx()',
    ],
    forbidden: ['while', 'function'],
  },
  {
    id: 'ch4',
    name: '第 4 章 · while + 嵌套 if',
    subtitle: '第 35~44 关',
    goal: '不再数次数：让英雄自己判断什么时候继续、什么时候停',
    allow: ['while 循环', '把 if 嵌进循环', 'break'],
    forbidden: ['function'],
  },
  {
    id: 'ch5',
    name: '第 5 章 · 综合大挑战',
    subtitle: '第 45~49 关',
    goal: '迷宫、怪物、尖刺混在一起，所有知识都可以用（含自定义函数）',
    allow: ['全部语法', '自定义函数'],
    forbidden: [],
  },
]

// ============================================================ 第 1 章 · 顺序编程
const CH1: LevelDef[] = [
  {
    id: 'level-1',
    chapter: 'ch1',
    name: '第 1 关 · 往前走',
    subtitle: '顺序执行',
    objective: '地牢的出口就在右边。让英雄一步一步走过去。',
    hints: [
      '代码是一行一行往下执行的：写一行 moveRight()，英雄就走一格。',
      '数一数英雄和出口之间隔了几格，就写几行。',
    ],
    newCommands: ['hero.moveRight()'],
    par: 10,
    map: [wall(12), '#@.......E.#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 让英雄走到出口', 'hero.moveRight()', ''].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-2',
    chapter: 'ch1',
    name: '第 2 关 · 向左走',
    subtitle: '反方向也是移动',
    objective: '出口在左边，用 moveLeft() 往回走。',
    hints: ['moveLeft() 向左走一格，和 moveRight() 刚好相反。'],
    newCommands: ['hero.moveLeft()'],
    par: 8,
    map: [wall(12), '#E.....@...#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 出口在左边', ''].join('\n'),
    solution: [
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
      'hero.moveLeft()',
    ].join('\n'),
  },
  {
    id: 'level-3',
    chapter: 'ch1',
    name: '第 3 关 · 往下走',
    subtitle: '第一次往下',
    objective: '出口在右下方：先往下走到最底，再往右走。路上那颗宝石走过去就会自动捡起来。',
    hints: [
      'moveDown() 让英雄往下走一格。写两行，它就走两格。',
      '出口在右下角：先往下走到底，再往右走。',
      '宝石不用特意去捡，走过去就自动到手了。',
    ],
    newCommands: ['hero.moveDown()'],
    par: 7,
    map: [wall(6), '#....#', '#....#', '#@...#', '#g...#', '#...E#', wall(6)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['// 先往下走，再往右走', ''].join('\n'),
    solution: [
      'hero.moveDown()',
      'hero.moveDown()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-4',
    chapter: 'ch1',
    name: '第 4 关 · 往上走',
    subtitle: '反方向往上',
    objective: '这次出口在上面：用 moveUp() 先往上走到底，再往右走到出口。',
    hints: [
      'moveUp() 让英雄往上走一格，和 moveDown() 刚好相反。',
      '先数一数要往上走几格，再数往右走几格。',
      '路上那颗宝石走过去就自动捡到了。',
    ],
    newCommands: ['hero.moveUp()'],
    par: 8,
    map: [wall(8), '#...E..#', '#......#', '#g.....#', '#@.....#', wall(8)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['// 先往上走，再往右走', ''].join('\n'),
    solution: [
      'hero.moveUp()',
      'hero.moveUp()',
      'hero.moveUp()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-5',
    chapter: 'ch1',
    name: '第 5 关 · 让英雄说话',
    subtitle: '第一次开口',
    objective: 'hero.say() 能让英雄说一句话，头顶会冒出一个气泡。先说一句话，再走到出口。',
    hints: [
      'hero.say("你好") 就是让英雄说出「你好」，说的话要用引号 " " 包起来。',
      '说一句话不花时间，也不会多算一步。',
      '说完话，再一路往右走到出口。',
    ],
    newCommands: ['hero.say("文字")'],
    par: 11,
    map: [wall(14), '#@..g.....E..#', wall(14)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['// 让英雄说一句话', '', '// 再一路往右走到出口', ''].join('\n'),
    solution: [
      'hero.say("我出发啦")',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-6',
    chapter: 'ch1',
    name: '第 6 关 · 看看前面有谁',
    subtitle: '认识 findNearestEnemy()',
    objective: '地牢里藏着一只食人魔。hero.findNearestEnemy() 会帮你找到离英雄最近的那个敌人。',
    hints: [
      'findNearestEnemy() 的意思是「找到离我最近的敌人」。它会告诉你那个敌人是谁。',
      '把它放进 say 里：hero.say(hero.findNearestEnemy())，英雄就会说出它的名字。',
      '这一关不用打架：沿着上面那一行绕过去，就能走到出口。',
    ],
    newCommands: ['hero.findNearestEnemy()'],
    par: 11,
    map: [wall(12), '#@........E#', '#...o......#', wall(12)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      '// 先找一找最近的敌人是谁，再让英雄说出来',
      '',
      '// 然后绕过去，走到出口',
      '',
    ].join('\n'),
    solution: [
      'hero.say(hero.findNearestEnemy())',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-7',
    chapter: 'ch1',
    name: '第 7 关 · 给敌人起个名字',
    subtitle: '第一次用 const',
    objective: '把找到的敌人存起来，起个名字叫「敌人」：const 敌人 = hero.findNearestEnemy()。',
    hints: [
      'const 的意思是「给它起个名字」。等号左边是名字，右边是要存起来的东西。',
      'const 敌人 = hero.findNearestEnemy() 读作：把找到的敌人，起名叫「敌人」。',
      '起好名字，叫一声 hero.say(敌人)，英雄就会报出它的名字。',
      '这一关还是不用打架，绕过去走到出口就行。',
    ],
    newCommands: ['const 敌人 = hero.findNearestEnemy()'],
    par: 13,
    map: [wall(14), '#@..........E#', '#...o........#', wall(14)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      '// 把找到的敌人起个名字，叫「敌人」',
      '',
      '// 叫一声它的名字，再走到出口',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.say(敌人)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-8',
    chapter: 'ch1',
    name: '第 8 关 · 打它',
    subtitle: '第一次攻击',
    objective: '食人魔挡在路中间，必须先打败它。走到它旁边，再用 hero.attack(敌人) 打它。',
    hints: [
      'attack 的意思是「攻击」。括号里写你要打谁：hero.attack(敌人)。',
      '不能站到敌人身上，走到它旁边就停下（差 1 格就能打到）。',
      '食人魔有 20 点血，英雄一刀砍 10 点，所以要砍两刀。',
    ],
    newCommands: ['hero.attack(敌人)'],
    par: 17,
    map: ['################', '#@...o........E#', '################'],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      '// 先找到敌人，给它起个名字',
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 走到它旁边，再打它',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-9',
    chapter: 'ch1',
    name: '第 9 关 · 它还剩多少血',
    subtitle: '看敌人的血量',
    objective: '敌人的血量会显示在它头顶。用 enemy.health 读出它还剩多少血，再打到它倒下。',
    hints: [
      '敌人.health（比如 敌人.health）是「它还剩下多少血」，会得到一个数字。',
      'hero.say(敌人.health) 能让英雄把血量报出来，你会看到一个数字。',
      '英雄一刀砍 10 点。血量掉到 0，它就倒下了。',
    ],
    newCommands: ['enemy.health'],
    par: 17,
    map: ['################', '#@....o.......E#', '################'],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      '// 先找到敌人，给它起个名字',
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 报一报它还有多少血，再走到旁边打它',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.say(敌人.health)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-10',
    chapter: 'ch1',
    name: '第 10 关 · 第一章大考验',
    subtitle: '把学过的都用上',
    objective: '一条很长的通道，路上有宝石、药水、小兽和食人魔。把第一章学的都用起来。',
    hints: [
      '宝石和药水不用特意去捡，走过去就自动到手了。',
      '先找到第一只敌人，打完再重新 findNearestEnemy() 找下一只。',
      '想看看敌人还剩多少血，用 hero.say(敌人.health) 报出来。',
      '这条路很长，慢慢写。写完就进入第 2 章啦。',
    ],
    par: 26,
    map: [wall(24), '#@..g..m...p...o...g..E#', wall(24)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: [
      '// 第一只：小兽',
      'const 小兽 = hero.findNearestEnemy()',
      '',
      '// 打完它，再找下一只',
      '',
    ].join('\n'),
    solution: [
      'const 小兽 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.attack(小兽)',
      'const 食人魔 = hero.findNearestEnemy()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.say(食人魔.health)',
      'hero.attack(食人魔)',
      'hero.attack(食人魔)',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
]

// ============================================================ 第 2 章 · for 循环
const CH2: LevelDef[] = [
  {
    id: 'level-11',
    chapter: 'ch2',
    name: '第 11 关 · 重复的力量',
    subtitle: 'for 循环入门',
    objective: '又长又直的一条走廊。这次用 for 循环，代替一大串重复的 moveRight()。',
    hints: [
      'for (let i = 0; i < 次数; i++) { ... } 里的代码会重复执行「次数」遍。',
      '数一数要走多少格，把它写进 i < 多少。',
    ],
    newCommands: ['for (let i = 0; i < 次数; i++) { ... }'],
    par: 19,
    map: [wall(20), '#@...........g....E#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 17; i++) {',
      '  // 这里写要让英雄重复做的事',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: ['for (let i = 0; i < 17; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-12',
    chapter: 'ch2',
    name: '第 12 关 · 两段路',
    subtitle: '一个循环管一段',
    objective: '先向右走到头，再向下走到底。两段路各写一个循环。',
    hints: ['两段次数不一样，就写两个循环。'],
    par: 20,
    map: [wall(20), '#@.................#', '#..................#', '#................E.#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['for (let i = 0; i < 16; i++) {', '  hero.moveRight()', '}', '', '// 再往下走', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 16; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 2; i++) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-13',
    chapter: 'ch2',
    name: '第 13 关 · 宝石队列',
    subtitle: '循环顺手捡宝石',
    objective: '四颗宝石整齐排在路上，用一个循环走到底。',
    hints: ['宝石是等距摆放的，所以一个循环就能全捡到。'],
    par: 17,
    map: [wall(19), '#@..g..g..g..g..E.#', wall(19)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: [
      '// 数一数这条路要走几格，把数字填进 i < ?',
      'for (let i = 0; i < 0; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: ['for (let i = 0; i < 15; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-14',
    chapter: 'ch2',
    name: '第 14 关 · 连击',
    subtitle: '用循环砍到倒下',
    objective: '食人魔王就站在旁边，血很厚。用循环连砍 6 刀，再走到出口。',
    hints: [
      '先用 findNearestEnemy() 把它存进变量，再在循环里反复攻击。',
      '战斗中它会还手，英雄掉血是正常的。',
    ],
    newCommands: ['把 hero.attack() 放进循环'],
    par: 26,
    map: [wall(20), '#@X...............E#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['const boss = hero.findNearestEnemy()', '', '// 在循环里攻击它', ''].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'for (let i = 0; i < 6; i++) {',
      '  hero.attack(boss)',
      '}',
      'for (let i = 0; i < 17; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-15',
    chapter: 'ch2',
    name: '第 15 关 · 走两步，砍两刀',
    subtitle: '循环里的固定节奏',
    objective: '四个食人魔等距离站岗。每轮「走两格 + 砍两刀」，循环四轮。',
    hints: ['循环体里可以写多行代码，它们会整段重复。'],
    newCommands: ['循环里可以写好几行'],
    par: 26,
    map: [wall(20), '#@..o.o.o.o.....E..#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 4; i++) {', '  // 走两步 + 砍两刀', '}', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  const 敌人 = hero.findNearestEnemy()',
      '  hero.attack(敌人)',
      '  hero.attack(敌人)',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-16',
    chapter: 'ch2',
    name: '第 16 关 · 边报数边前进',
    subtitle: '循环变量 i 会变',
    objective: '每捡一颗宝石就报一次数，用 hero.say() 说出现在是第几颗。',
    hints: [
      '循环变量 i 每一轮都会变化，可以直接拼进字符串。',
      '字符串拼接用 + ："第 " + i + " 颗宝石"。',
    ],
    newCommands: ['字符串拼接 "第 " + i'],
    par: 19,
    map: [wall(21), '#@.g..g..g..g..g..E.#', wall(21)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: ['for (let i = 1; i <= 5; i++) {', '  // 报数，然后走三格', '}', ''].join('\n'),
    solution: [
      'for (let i = 1; i <= 5; i++) {',
      '  hero.say("第 " + i + " 颗宝石")',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '}',
      'hero.moveRight()',
      'hero.moveRight()',
    ].join('\n'),
  },
  {
    id: 'level-17',
    chapter: 'ch2',
    name: '第 17 关 · L 形通道',
    subtitle: '两段不同次数',
    objective: '先向右走 5 格，再向下走 3 格到出口。',
    hints: ['两个循环，次数分别写在各自的条件里。'],
    par: 10,
    map: [wall(16), '#@.............#', '#..............#', '#..............#', '#.....E........#', wall(16)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['// 向右 5 格', '', '// 向下 3 格', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 5; i++) {',
      '  hero.moveRight()',
      '}',
      'for (let i = 0; i < 3; i++) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-18',
    chapter: 'ch2',
    name: '第 18 关 · 次数用变量',
    subtitle: '把数字取个名字',
    objective: '先用 let 把步数记下来，再让循环按这个变量走。',
    hints: [
      'let 步数 = 13 之后，循环条件里就能写 i < 步数。',
      '以后想让英雄多走两格，只改数字那一行就行。',
    ],
    newCommands: ['用变量当循环次数'],
    par: 15,
    map: [wall(20), '#@..........g.E....#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: [
      '// 先把要走几格存进变量，再让循环用它',
      'const 步数 = 0',
      '',
      'for (let i = 0; i < 步数; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: ['const 步数 = 13', 'for (let i = 0; i < 步数; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-19',
    chapter: 'ch2',
    name: '第 19 关 · 一排小兽',
    subtitle: '循环里的一刀流',
    objective: '四只小兽等距排列。每轮走两格、砍一刀，循环四轮。',
    hints: ['小兽只有 10 点血，一刀就够。'],
    par: 21,
    map: [wall(20), '#@..m.m.m.m.....E..#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['for (let i = 0; i < 4; i++) {', '  // 走两格 + 砍一刀', '}', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 4; i++) {',
      '  hero.moveRight()',
      '  hero.moveRight()',
      '  const 敌人 = hero.findNearestEnemy()',
      '  hero.attack(敌人)',
      '}',
      'for (let i = 0; i < 7; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-20',
    chapter: 'ch2',
    name: '第 20 关 · 长路用循环',
    subtitle: '一行代码走到底',
    objective: '这次走廊有 21 格，用循环一行搞定。',
    hints: ['回想第 1 关你写了多少行——这就是循环的价值。'],
    par: 24,
    map: [wall(24), '#@....................E#', wall(24)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      '// 这条走廊很长，用一个循环走完它',
      'for (let i = 0; i < 0; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: ['for (let i = 0; i < 21; i++) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-21',
    chapter: 'ch2',
    name: '第 21 关 · 先赶路再战斗',
    subtitle: '循环 + 战斗',
    objective: '先走 6 格（顺路捡宝石），再砍倒食人魔，最后走到出口。',
    hints: ['循环不只能包移动，也能包攻击。'],
    par: 16,
    map: [wall(16), '#@..g...o....E.#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: ['// 第一段：赶路', '', '// 第二段：战斗', '', '// 第三段：继续赶路', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'const 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-22',
    chapter: 'ch2',
    name: '第 22 关 · 第二章考验',
    subtitle: '走 - 打 - 走 - 打 - 走',
    objective: '宝石和食人魔交替出现，把整条路线用循环串起来。',
    hints: ['把路线拆成「赶路」和「战斗」两种段落，交替写。'],
    par: 29,
    map: [wall(26), '#@..g...o...g...o...g..E.#', wall(26)],
    enemiesStandStill: true,
    win: { killAll: true, collectAll: true, reachExit: true },
    starter: ['// 走 6 格 → 打 2 刀 → 走 8 格 → 打 2 刀 → 走 8 格', ''].join('\n'),
    solution: [
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'let 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
      '敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 3 章 · if 判断
const CH3: LevelDef[] = [
  {
    id: 'level-23',
    chapter: 'ch3',
    name: '第 23 关 · 你离我有多远',
    subtitle: '认识距离',
    objective: '英雄想知道敌人离自己有多远。用 hero.distanceTo(敌人) 读出距离，再走过去打它。',
    hints: [
      'hero.distanceTo(敌人) 会告诉你「离它还有几格」。',
      '距离是 1，说明它就在旁边；是 3，就是还差 3 格。',
      'hero.say(hero.distanceTo(敌人)) 能让英雄把距离报出来，你会看到一个数字。',
      '读完距离，再走到它旁边，打两刀，然后走到出口。',
    ],
    newCommands: ['hero.distanceTo(敌人)'],
    par: 15,
    map: [wall(14), '#@.o......E..#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 读一读：离敌人还有几格？',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'hero.say(hero.distanceTo(敌人))',
      'hero.moveRight()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-24',
    chapter: 'ch3',
    name: '第 24 关 · 够得着才出手',
    subtitle: '第一次写 if',
    objective: '太远就打不到。用 if 判断：如果离得太远，就先走近一步，再打它。',
    hints: [
      'if 就是「如果」。写法是：if (条件) { 要做的事 }。',
      'if 后面的大括号里，只在条件说得通的时候才会执行。',
      '这里的条件是比较大小：hero.distanceTo(敌人) > 1，意思是「离得比 1 格还远」。',
      '先写条件，再把「要做什么」写进大括号里。',
    ],
    newCommands: ['if (条件) { ... }'],
    par: 15,
    map: [wall(14), '#@.o......E..#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const 敌人 = hero.findNearestEnemy()',
      '',
      '// 如果离得太远，就先走近一步',
      '',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'if (hero.distanceTo(敌人) > 1) {',
      '  hero.moveRight()',
      '}',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'for (let i = 0; i < 8; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-25',
    chapter: 'ch3',
    name: '第 25 关 · 够不着，就走近点',
    subtitle: '第一次写 else',
    objective: '够得着就打它，够不着就走近一点。用 if 和 else 把这两种情况都写出来。',
    hints: [
      'else 是「不然」。if 和 else 只会做其中一个：if 的事没发生，才做 else 的事。',
      '读一读：如果够得着（距离不超过 1 格），就打它；不然，就走近一点。',
      '写完 if 的大括号，紧接着写 else，再写一对大括号。',
      '这一关不用走到出口：把小兽打倒，就算过关。',
    ],
    newCommands: ['else { ... }'],
    par: 5,
    map: [wall(14), '#@..m.......E#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true },
    starter: [
      'const 敌人 = hero.findNearestEnemy()',
      '',
      'for (let i = 0; i < 6; i++) {',
      '  if (hero.distanceTo(敌人) <= 1) {',
      '    ',
      '  } else {',
      '    ',
      '  }',
      '}',
      '',
    ].join('\n'),
    solution: [
      'const 敌人 = hero.findNearestEnemy()',
      'for (let i = 0; i < 6; i++) {',
      '  if (hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-26',
    chapter: 'ch3',
    name: '第 26 关 · 两个条件一起看',
    subtitle: '认识 &&',
    objective: '路上有两只敌人。先用 && 确认找到了敌人，再看它够不够近：够近就打，不够近就走。',
    hints: [
      '&& 读作「并且」。它把两个条件连起来，两个都说得通，整段才算数。',
      '敌人 && hero.distanceTo(敌人) <= 1 的意思是：先确认找到了敌人，再看它离得够不够近。',
      '前面的两小段里，任何一段不成立，后面的就不用算了，程序也不会出错。',
      '敌人全被打败后，findNearestEnemy() 会给一个空的（null），这时候就安安心心往右走。',
    ],
    newCommands: ['&& （两个条件都要满足）'],
    par: 18,
    map: [wall(20), '#@..m....o....E....#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 40; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  // 找到了敌人，而且它就在旁边，才出手',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 40; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-27',
    chapter: 'ch3',
    name: '第 27 关 · 右边能走吗',
    subtitle: '第一次用 canMoveRight()',
    objective: '通道走到尽头要往下拐。用 hero.canMoveRight() 问一问：右边能走吗？',
    hints: [
      'hero.canMoveRight() 会回答「能」或者「不能」：右边是墙、或者站着人，就回答不能。',
      '不能往右的时候，就用 else 往下走一格。',
      '这就是自动找路的开始：能右就右，不能就下。',
    ],
    newCommands: ['hero.canMoveRight()'],
    par: 8,
    map: [wall(6), '#@...#', '#....#', '#....#', '#...E#', wall(6)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'for (let i = 0; i < 12; i++) {',
      '  // 问一问：右边能走吗？能就走，不能就往下',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 12; i++) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.moveDown()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-28',
    chapter: 'ch3',
    name: '第 28 关 · 下面能走吗',
    subtitle: '第一次用 canMoveDown()',
    objective: '出口在正下方。用 hero.canMoveDown() 问一问：下面能走吗？不能往下，就往右走。',
    hints: [
      'hero.canMoveDown() 会回答「下面能不能走」。',
      '往下能走就一直往下，走到最底下一行，它会回答不能。',
      '这时候再用 else 往右走，一直到出口。',
    ],
    newCommands: ['hero.canMoveDown()'],
    par: 10,
    map: [wall(8), '#@.....#', '#......#', '#......#', '#.....E#', wall(8)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'for (let i = 0; i < 12; i++) {',
      '  // 问一问：下面能走吗？能就往下，不能就往右',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 12; i++) {',
      '  if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-29',
    chapter: 'ch3',
    name: '第 29 关 · 看到尖刺就绕开',
    subtitle: '第一次用 lookRight()',
    objective: '前方有两格尖刺，踩上去会掉血。用 hero.lookRight() 看清右边是什么，再决定怎么走。',
    hints: [
      'hero.lookRight() 会告诉你右边那一格有什么，答案是这些词之一："空地"、"墙"、"尖刺"、"敌人"、"物品"、"出口"。',
      'hero.lookRight() === "尖刺" 就是在问：右边是尖刺吗？',
      '看到尖刺，就先往下走到安全的一行绕过去。',
      '绕过去之后，别忘了回来打那只食人魔，再走到出口。',
    ],
    newCommands: ['hero.lookRight() === "尖刺"'],
    par: 17,
    map: [wall(14), '#@..^^...o..E#', '#............#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.moveRight()',
      '',
      '// 右边是尖刺吗？是的话就先下去',
      '',
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      '',
      '// 绕过来了，再去打食人魔',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'if (hero.lookRight() === "尖刺") {',
      '  hero.moveDown()',
      '}',
      'for (let i = 0; i < 6; i++) {',
      '  hero.moveRight()',
      '}',
      'const 敌人 = hero.findNearestEnemy()',
      'hero.attack(敌人)',
      'hero.attack(敌人)',
      'hero.moveUp()',
      'for (let i = 0; i < 3; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-30',
    chapter: 'ch3',
    name: '第 30 关 · 前面是墙就上来',
    subtitle: '用 lookRight() 看墙',
    objective: '上面那行全是尖刺。先下到安全的一行，走到尽头撞墙，再上来走到出口。',
    hints: [
      'hero.lookRight() === "墙" 表示前面没路了。',
      '先往下走一格，然后一直向右：撞墙就往上走一格。',
      '上来之后前面就通了，继续往右就是出口。',
    ],
    newCommands: ['hero.lookRight() === "墙"'],
    par: 21,
    map: [wall(20), '#@..^^^^^^^^......E#', '#..................#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'hero.moveDown()',
      '',
      'for (let i = 0; i < 25; i++) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveDown()',
      'for (let i = 0; i < 25; i++) {',
      '  if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-31',
    chapter: 'ch3',
    name: '第 31 关 · 三种情况',
    subtitle: '第一次用 else if',
    objective: '右边可能是尖刺，也可能是墙，还可能什么都没有。三种情况，三种做法。',
    hints: [
      'else if 是「不然再看看」。它接着 if 往下问第二种情况。',
      '顺序很重要：先看是不是尖刺，再看是不是墙，都不是就往前走。',
      '只要有一个对上了，后面的就不用再看了。',
    ],
    newCommands: ['if / else if / else'],
    par: 21,
    map: [wall(20), '#@..^^^^^^^^......E#', '#...........####...#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'for (let i = 0; i < 40; i++) {',
      '  if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  }',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 40; i++) {',
      '  if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-32',
    chapter: 'ch3',
    name: '第 32 关 · 我掉了多少血',
    subtitle: '第一次用 hero.health',
    objective: '英雄被小兽咬了一口。用 hero.health 读一读自己还剩多少血，再打完它去出口。',
    hints: [
      'hero.health 是英雄自己还剩的血，满血是 100。',
      '受伤以后这个数字会变小。hero.say(hero.health) 能把血量报出来。',
      '小兽只有 10 点血，英雄一刀就够。',
    ],
    newCommands: ['hero.health'],
    par: 15,
    map: [wall(16), '#@..m........E.#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.moveRight()',
      '',
      '// 报一报自己还剩多少血',
      '',
      '',
      '// 再打掉面前的小兽',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.moveRight()',
      'hero.say(hero.health)',
      'hero.attack(hero.findNearestEnemy())',
      'for (let i = 0; i < 10; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-33',
    chapter: 'ch3',
    name: '第 33 关 · 血没满就补一补',
    subtitle: '第一次用 hero.maxHealth',
    objective: '出门先挨了一下。用 hero.maxHealth 比一比：血没满就下去喝药水，满了就直接走。',
    hints: [
      'hero.maxHealth 是血量上限，也就是满血的那个数（100）。',
      'if (hero.health < hero.maxHealth) 的意思是：比满血少，就是掉过血了。',
      '掉血了就下去喝药水，再上来继续走。',
      '路上还有一只食人魔，打两刀就倒下。',
    ],
    newCommands: ['hero.maxHealth'],
    par: 23,
    map: [wall(18), '#@.m....o.......E#', '#....p...........#', wall(18)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'hero.moveRight()',
      'hero.attack(hero.findNearestEnemy())',
      '',
      '// 血没满就下去喝药水',
      '',
    ].join('\n'),
    solution: [
      'hero.moveRight()',
      'hero.attack(hero.findNearestEnemy())',
      'if (hero.health < hero.maxHealth) {',
      '  hero.moveDown()',
      '  for (let i = 0; i < 3; i++) {',
      '    hero.moveRight()',
      '  }',
      '  hero.moveUp()',
      '}',
      'for (let i = 0; i < 2; i++) {',
      '  hero.moveRight()',
      '}',
      'hero.attack(hero.findNearestEnemy())',
      'hero.attack(hero.findNearestEnemy())',
      'for (let i = 0; i < 9; i++) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-34',
    chapter: 'ch3',
    name: '第 34 关 · 第三章考验',
    subtitle: '一条长防线',
    objective: '三个食人魔依次守着通道。够得着就打，够不着就往前走，一路推进到出口。',
    hints: [
      '套路就是：够得着就打，够不着就走。',
      '别忘了前面的 && ：先确认找到了敌人，再看它够不够近。',
      '打光以后 findNearestEnemy() 会给你一个空的，那时候就安心往右走。',
    ],
    par: 30,
    map: [wall(25), '#@...o....o....o......E.#', wall(25)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'for (let i = 0; i < 60; i++) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 4 章 · while + 嵌套 if
const CH4: LevelDef[] = [
  {
    id: 'level-35',
    chapter: 'ch4',
    name: '第 35 关 · 一直向前',
    subtitle: 'while (true)',
    objective: '不用数格子了：让英雄一直往前走，走到出口任务就自动结束。',
    hints: [
      'while (true) { ... } 会一直重复，直到任务完成或英雄倒下。',
      '不用担心停不下来：踩上出口的那一瞬间程序就结束了。',
    ],
    newCommands: ['while (true) { ... }'],
    par: 18,
    map: [wall(20), '#@...............E.#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'while (true) {',
      '  // 让英雄一直往前走',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: ['while (true) {', '  hero.moveRight()', '}'].join('\n'),
  },
  {
    id: 'level-36',
    chapter: 'ch4',
    name: '第 36 关 · 走到指定位置',
    subtitle: 'while + 坐标条件',
    objective: '用位置当条件：先向右走到第 10 列，再向下走到出口，位置到了循环就自己停。',
    hints: [
      'hero.pos.x 是英雄现在在第几列，hero.pos.y 是第几行。',
      'while (hero.pos.x < 10) 表示「还没到第 10 列就继续走」，到了就停下来。',
      '第二段路同理：还没到第 4 行就继续往下走。',
    ],
    newCommands: ['hero.pos.x（英雄在第几列）'],
    par: 14,
    map: [wall(16), '#@.............#', '#..............#', '#..............#', '#.........E....#', wall(16)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      '// 还没到第 10 列，就一直往右走',
      '',
      '',
      '// 再往下走到出口',
      '',
    ].join('\n'),
    solution: [
      'while (hero.pos.x < 10) {',
      '  hero.moveRight()',
      '}',
      'while (hero.pos.y < 4) {',
      '  hero.moveDown()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-37',
    chapter: 'ch4',
    name: '第 37 关 · 边走边打',
    subtitle: 'if 嵌在 while 里',
    objective: '小兽会主动扑过来。循环里判断：够得着就打，够不着就继续走。',
    hints: ['这就是自动战斗的雏形：一个 while 包住「观察 → 决定 → 行动」。'],
    newCommands: ['while + if 嵌套'],
    par: 21,
    map: [wall(20), '#@..m...m...m....E.#', wall(20)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-38',
    chapter: 'ch4',
    name: '第 38 关 · 收集到底',
    subtitle: 'while + findNearestItem',
    objective: '用 while (hero.findNearestItem()) 一直捡，直到宝石全都到手。',
    hints: [
      'findNearestItem() 找不到东西时返回 null，条件不成立，循环就结束了。',
      '捡完之后还要走到出口。',
    ],
    newCommands: ['while (hero.findNearestItem())'],
    par: 18,
    map: [wall(20), '#@..g...g...g....E.#', wall(20)],
    enemiesStandStill: true,
    win: { collectAll: true, reachExit: true },
    starter: [
      '// 还有宝石就一直往右走，把宝石捡光',
      '',
      '',
      '',
      '// 再去出口',
      '',
    ].join('\n'),
    solution: [
      'while (hero.findNearestItem()) {',
      '  hero.moveRight()',
      '}',
      'while (hero.pos.x < 18) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-39',
    chapter: 'ch4',
    name: '第 39 关 · 打到它倒下',
    subtitle: 'while + 血量条件',
    objective: '用 boss.health > 0 当作循环条件，打到它倒下为止。',
    hints: ['while (boss.health > 0) 比写死「打 6 刀」更聪明：换个血量的敌人也不用改代码。'],
    newCommands: ['while (boss.health > 0)'],
    par: 26,
    map: [wall(20), '#@X...............E#', wall(20)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'const boss = hero.findNearestEnemy()',
      '',
      '// 只要它还有血，就一直打它',
      '  ',
      '',
    ].join('\n'),
    solution: [
      'const boss = hero.findNearestEnemy()',
      'while (boss.health > 0) {',
      '  hero.attack(boss)',
      '}',
      'while (hero.pos.x < 18) {',
      '  hero.moveRight()',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-40',
    chapter: 'ch4',
    name: '第 40 关 · 迷宫入门',
    subtitle: '自动探索',
    objective: '看不见全图也没关系：能右转就右转，不能就往下走，一路摸到出口。',
    hints: [
      'while (true) 里先判断 canMoveRight()，再判断 canMoveDown()，都不行就 break 结束。',
      'break 表示跳出循环。',
    ],
    newCommands: ['break'],
    par: 11,
    map: [wall(10), '#@.......#', '#.#####..#', '#.......E#', wall(10)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'while (true) {',
      '  // 能右就右，不能就下，都不行就停下来',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-41',
    chapter: 'ch4',
    name: '第 41 关 · 尖刺回廊（自动版）',
    subtitle: 'while + look',
    objective: '上面一行全是尖刺。先下到安全通道，一路向右，撞墙就上。',
    hints: ['这次不用数次数，把第 30 关的思路换成 while 就行。'],
    par: 21,
    map: [wall(20), '#@..^^^^^^^^......E#', '#..................#', wall(20)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: [
      'hero.moveDown()',
      '',
      'while (true) {',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'hero.moveDown()',
      'while (true) {',
      '  if (hero.lookRight() === "墙") {',
      '    hero.moveUp()',
      '  } else {',
      '    hero.moveRight()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-42',
    chapter: 'ch4',
    name: '第 42 关 · 迷宫进阶',
    subtitle: '迷宫 + 守卫',
    objective: '迷宫里藏着一只小兽。先解决它，再继续摸索出口。',
    hints: ['把「打敌人」放在最优先：距离 1 就先砍，其次才是走路。'],
    par: 14,
    map: [wall(12), '#@....m....#', '#.#######..#', '#.........E#', wall(12)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-43',
    chapter: 'ch4',
    name: '第 43 关 · 巡逻队',
    subtitle: '会追人的敌人',
    objective: '三种敌人都会主动扑上来。一路推进，把它们清干净。',
    hints: [
      '敌人会跟着你走，所以不用追它，站住反击也行。',
      '走到墙边还有敌人没解决时，用 hero.wait() 原地等它过来。',
    ],
    newCommands: ['hero.wait()'],
    par: 29,
    map: [wall(24), '#@...o....m....o......E#', wall(24)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.wait()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-44',
    chapter: 'ch4',
    name: '第 44 关 · 第四章考验',
    subtitle: '看路 + 打架',
    objective: '尖刺和守卫一起出现。先绕尖刺、顺手清怪，最后爬上出口。',
    hints: ['判断顺序很重要：能打就打，其次躲尖刺，再其次往前走，最后才考虑上下。'],
    par: 25,
    map: [wall(22), '#@..^^..m...........E#', '#....................#', wall(22)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  ',
      '}',
      '',
    ].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
]

// ============================================================ 第 5 章 · 综合大挑战
const CH5: LevelDef[] = [
  {
    id: 'level-45',
    chapter: 'ch5',
    name: '第 45 关 · 迷宫 I',
    subtitle: '综合挑战',
    objective: '尖刺、拐角、守卫都在。用一套「先看、再打、再走」的循环走出去。',
    hints: [
      '判断顺序建议：够得着就打 → 前方尖刺就绕 → 能右转就右转 → 能下行就下行。',
      '这一章开始可以用 function 把常用判断打包起来。',
    ],
    par: 17,
    map: [wall(14), '#@..^^.......#', '#....##......#', '#....##......#', '#.......m...E#', wall(14)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  const 敌人 = hero.findNearestEnemy()', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-46',
    chapter: 'ch5',
    name: '第 46 关 · 怪物军团',
    subtitle: '血量和药水',
    objective: '一队怪物会主动扑上来，路上有瓶药水。血少了先补，再继续推进。',
    hints: [
      'if (hero.health < 60) 可以当作「该补血了」的信号。',
      '被围住时先对付最近的敌人，别硬冲。',
    ],
    par: 28,
    map: [wall(24), '#@..m...o...m...p.....E#', wall(24)],
    enemiesStandStill: false,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  const 敌人 = hero.findNearestEnemy()', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.health < 60 && hero.findNearestItem()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else {',
      '    hero.wait()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-47',
    chapter: 'ch5',
    name: '第 47 关 · 尖刺回廊 II',
    subtitle: '会受点伤的路线',
    objective: '上排尖刺很长，下排被墙截断。找机会穿过去，拿上药水再走到出口。',
    hints: [
      '有时不得不踩一次尖刺（-5 血），这比绕远路划算。',
      '判断顺序：打怪 → 尖刺就下 → 能右就右 → 能上就上 → 能下就下。',
    ],
    par: 26,
    map: [wall(24), '#@..^^^^^^^^....p.....E#', '#...........##.........#', wall(24)],
    enemiesStandStill: true,
    win: { reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.lookRight() === "尖刺") {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-48',
    chapter: 'ch5',
    name: '第 48 关 · 迷宫 II',
    subtitle: '两段下降',
    objective: '这条迷宫要连着往下拐两次，路上还藏着守卫。',
    hints: ['迷宫里不需要「向左」：一路右、下、上就能到出口。'],
    par: 18,
    map: [wall(16), '#@.....#.......#', '#......#.......#', '#......#.......#', '#.....^^..m..E.#', wall(16)],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else if (hero.canMoveUp()) {',
      '    hero.moveUp()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    id: 'level-49',
    chapter: 'ch5',
    name: '第 49 关 · 终局：地牢深处',
    subtitle: '全部知识',
    objective: '最后一战：走廊上有两只怪、一瓶药水，尽头是一段向下的秘密通道。',
    hints: [
      '把所有套路串起来：观察、判断、行动，循环到出口为止。',
      '想想能不能用 function 把「打怪」这一段包起来，代码会更短。',
    ],
    par: 30,
    map: [
      wall(24),
      '#@..m....o.......p.....#',
      '#.###################..#',
      '#.###################..#',
      '#.....................E#',
      wall(24),
    ],
    enemiesStandStill: true,
    win: { killAll: true, reachExit: true },
    starter: ['while (true) {', '  ', '}', ''].join('\n'),
    solution: [
      'while (true) {',
      '  const 敌人 = hero.findNearestEnemy()',
      '  if (敌人 && hero.distanceTo(敌人) <= 1) {',
      '    hero.attack(敌人)',
      '  } else if (hero.canMoveRight()) {',
      '    hero.moveRight()',
      '  } else if (hero.canMoveDown()) {',
      '    hero.moveDown()',
      '  } else {',
      '    break',
      '  }',
      '}',
    ].join('\n'),
  },
]

export const LEVELS: LevelDef[] = [...CH1, ...CH2, ...CH3, ...CH4, ...CH5]

// 把章节的语法锁同步到每一关，避免每关重复写一遍
for (const level of LEVELS) {
  const chapter = CHAPTERS.find((item) => item.id === level.chapter)
  level.forbidden = (chapter?.forbidden ?? []) as LanguageFeature[]
}

export function findLevel(id: string): LevelDef | undefined {
  return LEVELS.find((level) => level.id === id)
}

export function findChapter(id: string): ChapterDef | undefined {
  return CHAPTERS.find((chapter) => chapter.id === id)
}

export function levelsOfChapter(chapterId: string): LevelDef[] {
  return LEVELS.filter((level) => level.chapter === chapterId)
}
